name: front_end
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  bitsdojo_window: ^0.1.0
  fluent_ui: ^4.4.0
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.3
  provider: ^6.0.0
  logging: ^1.2.0
  window_manager: ^0.4.3
  file_picker: ^8.1.4
  web_socket_channel: ^3.0.1
  url_launcher: ^6.0.20
  path_provider: ^2.0.15
  path: ^1.9.0  # Adjusted to be compatible with flutter_test
  async: ^2.1.0 # Adjusted to be compatible with flutter_test
  characters: ^1.3.0  # Adjusted to be compatible with flutter_test
  clock: ^1.1.1 # Adjusted to be compatible with flutter_test
  collection: ^1.19.0 # Adjusted to be compatible with flutter_test
  intl: ^0.19.0 # Adjusted to be compatible with flutter_test
  material_color_utilities: ^0.11.1 # Adjusted to be compatible with flutter_test
  meta: ^1.15.0 # Adjusted to be compatible with flutter_test
  source_span: ^1.10.0  # Adjusted to be compatible with flutter_test
  stream_channel: ^2.1.2  # Adjusted to be compatible with flutter_test
  string_scanner: 1.3.0 # Adjusted to be compatible with flutter_test
  term_glyph: 1.2.1 # Adjusted to be compatible with flutter_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  boolean_selector: ^2.1.1 # Adjusted to be compatible with flutter_test
  fake_async: ^1.3.1 # Adjusted to be compatible with flutter_test
  leak_tracker: ^10.0.7 # Adjusted to be compatible with flutter_test
  leak_tracker_flutter_testing: ^3.0.8 # Adjusted to be compatible with flutter_test
  matcher: ^0.12.16+1  # Adjusted to be compatible with flutter_test
  stack_trace: ^1.12.0  # Adjusted to be compatible with flutter_test
  test_api: ^0.7.3
  vm_service: ^14.3.0 # Adjusted to be compatible with leak_tracker
  audioplayers: ^6.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/headphones.svg
    - assets/headphones.ico
    - assets/mp3.ico
    - assets/wav.ico
    - assets/fonts/
    - assets/vinyl-100.png
  
  fonts:
    - family: Roboto  
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf 
          weight: 400 
        - asset: assets/fonts/roboto/Roboto-Bold.ttf 
          weight: 700
    
    - family: Roboto Mono  
      fonts:
        - asset: assets/fonts/roboto/RobotoMono-VariableFont_wght.ttf
    
    - family: Source Code Pro  
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont_wght.ttf
    
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode-VariableFont_wght.ttf
    
    - family: Inconsolata  
      fonts:
        - asset: assets/fonts/Inconsolata-VariableFont_wdth,wght.ttf
    
    - family: National Park  
      fonts:
        - asset: assets/fonts/national-park/NationalPark-Regular.otf
          weight: 400
        - asset: assets/fonts/national-park/NationalPark-Heavy.otf
          weight: 700
        - asset: assets/fonts/national-park/NationalPark-Thin.otf
          weight: 100
    
    - family: Bookmark  
      fonts:
        - asset: assets/fonts/bookmark.ttf
    - family: BouCollege  
      fonts:
        - asset: assets/fonts/BouCollege.ttf
    - family: Coutline  
      fonts:
        - asset: assets/fonts/Coutline.ttf
    - family: Crakos  
      fonts:
        - asset: assets/fonts/Crakos.ttf
    - family: High Def  
      fonts:
        - asset: assets/fonts/High Def.ttf
    - family: Monaco  
      fonts:
        - asset: assets/fonts/Monaco.ttf
        
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
